<?php

/**
 * Remove inline styling added by Improved theme settings
 * (cf. modules/custom/improved_theme_settings/improved_theme_settings.module)
 *
 * @implements hook_page_attachments_alter().
 */
function nscn_frontend_page_attachments_alter(array &$attachments) {
  if (isset($attachments['#attached']['html_head']) && is_array($attachments['#attached']['html_head'])) {
    $attachments['#attached']['html_head'] = array_filter($attachments['#attached']['html_head'], function ($item) {
      return !isset($item[1]) || $item[1] !== 'social_theme_preprocess';
    });
  }
}
